import http from 'node:http';import {readFile,mkdir} from 'node:fs/promises';import {randomBytes,timingSafeEqual} from 'node:crypto';import {spawn,execFileSync} from 'node:child_process';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {createAuth} from './src/auth.mjs';import {InterviewStore,topics,selectModel} from './src/conversation.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));const port=Number(process.env.HITOTSUZUTSU_PORT||43127);const origin=`http://127.0.0.1:${port}`;const dataDir=process.env.HITOTSUZUTSU_DATA_DIR||path.join(root,'.local');const auth=createAuth(root,dataDir);const questions=JSON.parse(await readFile(path.join(root,'src/questions.json'),'utf8'));const interviews=new InterviewStore(path.join(dataDir,'conversations'),questions);const browserSessions=new Map();let modelCatalog=[];let modelCatalogProfile=null;let voiceOwner=null;let voiceChild=null;let modelChoice=null;let speechChild=null;
const cookieName='hitotsuzutsu_session';const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Cross-Origin-Resource-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; media-src 'self' blob:; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"};
function reply(res,status,data,extra={}){res.writeHead(status,{...headers,'Content-Type':'application/json;charset=utf-8',...extra});res.end(JSON.stringify(data))}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>20000)throw Object.assign(Error(),{code:'body_limit'})}return JSON.parse(text||'{}')}
function browserSession(req){const raw=req.headers.cookie||'';const token=raw.split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);return token?browserSessions.get(token):null}
function issueSession(res){const token=randomBytes(32).toString('hex');const session={csrf:randomBytes(32).toString('hex')};browserSessions.set(token,session);res.setHeader('Set-Cookie',`${cookieName}=${token}; HttpOnly; SameSite=Strict; Path=/`);return session}
async function safeStatus(){const s=await auth.client.getSession();return {status:s.status,sharing:s.sharing,profileLabel:s.profileLabel??null,identity:s.identity?{name:s.identity.name??null,email:s.identity.email??null}:null,signingIn:auth.getPending().signingIn,errorCode:auth.getPending().errorCode,voice:{engine:'macos-on-device',available:process.platform==='darwin'},mode:'chatgpt-plan'}}
async function requireProfile(){const s=await auth.client.getSession();if(s.status!=='connected'||!s.sharing||!s.profileId)throw Object.assign(Error(),{code:'sign_in_required'});return s.profileId}
async function models(profile){if(profile!==modelCatalogProfile||!modelCatalog.length){modelCatalog=await auth.client.listModels();modelCatalogProfile=profile;modelChoice=null}return modelCatalog}
function errorMessage(code){const map={sign_in_required:'このサイトでChatGPTにサインインしてください。',sharing_not_enabled:'ChatGPTの利用枠を使う許可がまだありません。接続を確認してください。',subscription_sharing_usage_limit_exceeded:'ChatGPTの利用枠に達しました。回答は保存されています。',subscription_sharing_usage_unavailable:'現在このアカウントの利用枠を使えません。利用状況を確認してください。',busy:'前の返答を待っています。',cancelled:'返答を止めました。回答は保存されています。',invalid_reply:'返答を整理できませんでした。回答は保存されています。',credential_storage_unavailable:'Macの認証情報保存を利用できませんでした。',body_limit:'一度に送る文章を短くしてください。'};return map[code]||'接続を完了できませんでした。入力はそのまま残しています。'}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,origin);if(req.headers.host!==`127.0.0.1:${port}`){reply(res,403,{error:'invalid_host'});return}let browser=browserSession(req);
try{
 if(req.method==='GET'&&url.pathname==='/'){browser ||=issueSession(res);res.writeHead(200,{...headers,'Content-Type':'text/html;charset=utf-8'});res.end(await readFile(path.join(root,'src/ui.html')));return}
 if(req.method==='GET'&&url.pathname==='/client.js'){res.writeHead(200,{...headers,'Content-Type':'text/javascript;charset=utf-8'});res.end(await readFile(path.join(root,'src/client.js')));return}
 if(!url.pathname.startsWith('/api/')){reply(res,404,{error:'not_found'});return}
 if(!browser){reply(res,401,{error:'browser_session_required'});return}
 if(req.headers.origin&&req.headers.origin!==origin){reply(res,403,{error:'origin_rejected'});return}
 if(req.method==='POST'&&(!equal(req.headers['x-csrf-token'],browser.csrf)||req.headers.origin!==origin)){reply(res,403,{error:'origin_rejected'});return}
 if(req.method==='GET'&&url.pathname==='/api/status'){reply(res,200,{...(await safeStatus()),csrf:browser.csrf});return}
 if(req.method==='GET'&&url.pathname==='/api/auth/pending'){const p=auth.getPending();reply(res,200,{url:p.url,errorCode:p.errorCode,signingIn:p.signingIn});return}
 if(req.method==='POST'&&url.pathname==='/api/auth/start'){await body(req);reply(res,202,await auth.start());return}
 if(req.method==='POST'&&url.pathname==='/api/auth/cancel'){await body(req);auth.client.cancelSignIn();auth.clearUrl();reply(res,200,{cancelled:true});return}
 if(req.method==='POST'&&url.pathname==='/api/auth/disconnect'){await body(req);if(voiceChild)voiceChild.kill();await auth.client.disconnect();modelCatalog=[];modelChoice=null;reply(res,200,{disconnected:true});return}
 const profile=await requireProfile();
 if(req.method==='GET'&&url.pathname==='/api/models'){const catalog=await models(profile);reply(res,200,{models:catalog,selected:modelChoice||selectModel(catalog)});return}
 if(req.method==='GET'&&url.pathname==='/api/record'){reply(res,200,await interviews.read(profile));return}
 if(req.method==='POST'&&url.pathname==='/api/chat'){const b=await body(req);if(typeof b.text!=='string'||!b.text.trim()||b.text.length>6000||!Object.hasOwn(topics,b.topic)||!['answer','skip'].includes(b.action)||typeof b.requestId!=='string'||!/^[a-zA-Z0-9-]{16,80}$/.test(b.requestId)){reply(res,400,{error:'invalid_input'});return}const catalog=await models(profile);const chosen=b.model||modelChoice||selectModel(catalog);if(!catalog.some(m=>m.slug===chosen)){reply(res,400,{error:'model_unavailable'});return}modelChoice=chosen;const ctrl=new AbortController();res.on('close',()=>{if(!res.writableEnded)ctrl.abort()});const result=await interviews.talk(profile,b,auth.client,chosen,ctrl.signal);reply(res,200,result);return}
 if(req.method==='POST'&&url.pathname==='/api/speak'){const b=await body(req);const record=await interviews.read(profile);const entry=record.messages.find(m=>m.id===b.messageId&&m.role==='assistant');if(!entry){reply(res,400,{error:'unknown_message'});return}if(speechChild)speechChild.kill();const child=spawn('/usr/bin/say',['-v','Kyoko','-r','175'],{stdio:['pipe','ignore','pipe']});speechChild=child;child.stderr.resume();child.stdin.on('error',()=>{});child.stdin.end(entry.text);child.on('error',()=>{if(!res.writableEnded)reply(res,502,{error:'speech_unavailable'})});child.on('exit',code=>{if(speechChild===child)speechChild=null;if(!res.writableEnded&&!res.destroyed)reply(res,200,{spoken:code===0})});res.on('close',()=>{if(!res.writableEnded)child.kill()});return}
 if(req.method==='POST'&&url.pathname==='/api/stop-audio'){await body(req);voiceChild?.kill();speechChild?.kill();reply(res,200,{stopped:true});return}
 if(req.method==='POST'&&url.pathname==='/api/voice'){await body(req);if(voiceChild){reply(res,409,{error:'microphone_in_use'});return}voiceOwner=browser;const child=spawn(path.join(root,'bin/VoiceBridge.app/Contents/MacOS/VoiceBridge'),[],{stdio:['ignore','pipe','pipe']});voiceChild=child;res.writeHead(200,{...headers,'Content-Type':'application/x-ndjson'});child.stdout.on('data',d=>{if(!res.destroyed)res.write(d)});child.stderr.resume();child.on('error',()=>{if(!res.destroyed){res.write(JSON.stringify({type:'error',code:'voice_unavailable'})+'\n');res.end()}});child.on('exit',()=>{if(voiceChild===child){voiceChild=null;voiceOwner=null}if(!res.destroyed)res.end()});res.on('close',()=>{child.kill();if(voiceChild===child){voiceChild=null;voiceOwner=null}});return}
 reply(res,404,{error:'not_found'});
}catch(e){if(!res.headersSent)reply(res,e.code==='sign_in_required'?401:e.code==='busy'?409:502,{error:typeof e.code==='string'?e.code:'request_failed',message:errorMessage(e.code)});else if(!res.destroyed)res.end()}});
server.listen(port,'127.0.0.1',()=>console.log(origin));
function stop(){voiceChild?.kill();speechChild?.kill();auth.client.cancelSignIn();server.close();process.exit(0)}process.on('SIGTERM',stop);process.on('SIGINT',stop);
