import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile,writeFile,mkdir,symlink} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';
import {Vault} from '../src/core/vault.mjs';import {LegacyImporter} from '../src/server/legacy.mjs';import {InterviewService} from '../src/server/interview.mjs';
const password='durability fixture password';
async function fixture(t){const dir=await mkdtemp(path.join(os.tmpdir(),'hz-durable-'));const v=new Vault(path.join(dir,'vault'));await v.create(password);t.after(async()=>{v.close();await rm(dir,{recursive:true,force:true})});return {v,dir};}
test('process death before commit rolls back, after ACK preserves capture and pause',async t=>{const {v,dir}=await fixture(t);new InterviewService(v,{}).navigate({operationId:'pause',action:'pause'});v.close();const source=pathToFileURL(path.resolve('src/core/vault.mjs')).href;
for(const stage of ['before','after']){const code=`import {Vault} from ${JSON.stringify(source)};const v=new Vault(${JSON.stringify(path.join(dir,'vault'))});await v.unlock(${JSON.stringify(password)});${stage==='before'?`v.mutate('crash',{type:'fixture'},s=>{s.conversation.question='UNCOMMITTED';process.kill(process.pid,'SIGKILL')})`:`v.capture({operationId:'acked',kind:'text',text:'ACKED SYNTHETIC',speaker:'self'});process.stdout.write('ACK');process.kill(process.pid,'SIGKILL')`}`;const result=spawnSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8'});assert.equal(result.signal,'SIGKILL');await v.unlock(password);assert.notEqual(v.read().conversation.question,'UNCOMMITTED');assert.equal(v.read().inquiry.paused,true);if(stage==='after'){assert.equal(result.stdout,'ACK');assert.equal(v.view().messages[0].text,'ACKED SYNTHETIC')}v.close();}});
test('recovery code changes wrapping passphrase while preserving encrypted answers',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'hz-recover-'));const v=new Vault(dir);t.after(async()=>{v.close();await rm(dir,{recursive:true,force:true})});const {recoveryCode}=await v.create(password,{recovery:true});v.capture({operationId:'capture',kind:'text',text:'復旧確認用。'});v.lock();await assert.rejects(v.recover('wrong recovery string','replacement password'),{code:'recovery_failed'});await v.recover(recoveryCode,'replacement password');assert.equal(v.view().messages[0].text,'復旧確認用。');v.lock();await assert.rejects(v.unlock(password),{code:'unlock_failed'});await v.unlock('replacement password');assert.equal(v.view().messages.length,1);});
test('legacy import is explicit, non-destructive, unconfirmed and deduplicated',async t=>{const {v,dir}=await fixture(t);const legacyDir=path.join(dir,'conversations');await mkdir(legacyDir);const id='a'.repeat(64),filename=path.join(legacyDir,id+'.json');const content=JSON.stringify({schema:'hitotsuzutsu/3',messages:[{id:'old-u',role:'user',kind:'raw_answer',text:'以前の回答。',captured_at:'2026-01-01T00:00:00Z'},{role:'assistant',text:'以前の案。'}],question_states:{Q001:{state:'answered',evidence:'以前の回答。'}}});await writeFile(filename,content);await symlink(filename,path.join(legacyDir,'b'.repeat(64)+'.json'));const importer=new LegacyImporter(legacyDir,v);assert.equal((await importer.list()).length,1);await assert.rejects(importer.import('../outside'));assert.equal(v.view().messages.length,0);const report=await importer.import(id);assert.equal(report.importedSources,1);assert.equal(v.view().knowledge.length,0);const source=Object.values(v.read().sources)[0];assert.equal(source.policy.model,false);assert.equal(v.read().inquiry.version,undefined);await importer.import(id);assert.equal(v.view().messages.length,2);assert.equal(await readFile(filename,'utf8'),content);v.deleteSource({operationId:randomUUID(),id:source.id,expectedRevision:1});assert(!JSON.stringify(v.read()).includes('以前の'));});
test('independent repeated words are separate utterances, retry keeps original identity',async t=>{const {v}=await fixture(t);const input={operationId:'one',kind:'text',text:'同じ発言。'};const one=v.capture(input),retry=v.capture(input),two=v.capture({...input,operationId:'two'});assert.equal(one.sourceId,retry.sourceId);assert.notEqual(one.sourceId,two.sourceId);assert.equal(Object.keys(v.read().sources).length,2);});
