import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {Vault} from '../src/core/vault.mjs';import {InterviewService} from '../src/server/interview.mjs';
const password='fixture password';const pause={reply:'ここで区切りましょう。',question:'',questionId:null,move:'pause',pause:true,proposals:[],coverage:[]};
async function fixture(t){const dir=await mkdtemp(path.join(os.tmpdir(),'hz-interview-')),vault=new Vault(dir);await vault.create(password);const provider={status:async()=>({connected:true,sharing:true,connectionId:'fixture'}),respond:async()=>({text:JSON.stringify(pause)})};const service=new InterviewService(vault,provider);vault.setConsent(true,'fixture');t.after(async()=>{service.cancelAll();vault.close();await rm(dir,{recursive:true,force:true})});const capture=(text='架空の回答。')=>vault.capture({operationId:randomUUID(),text,kind:'text',speaker:'self',purpose:'self_reflection',topic:'free'});const request=source=>({operationId:randomUUID(),...source,topic:'free',purpose:'self_reflection'});return {vault,provider,service,capture,request};}
test('offline durable capture survives provider failure and later retry does not duplicate',async t=>{const {vault,provider,service,capture,request}=await fixture(t);const source=capture(),r=request(source);provider.respond=async()=>{throw Error('fixture failure')};await assert.rejects(service.talk(r));assert.equal(Object.keys(vault.read().sources).length,1);provider.respond=async()=>({text:JSON.stringify(pause)});const done=await service.talk(r);assert(done.answer.pause);await service.talk(r);assert.equal(vault.view().messages.filter(m=>m.role==='assistant').length,1)});
test('model cannot reopen refused topics or grant authority; repair is bounded',async t=>{const {vault,provider,service,capture,request}=await fixture(t);let calls=0;provider.respond=async()=>{calls++;return {text:JSON.stringify({...pause,confirmed:true})}};await assert.rejects(service.talk(request(capture())),{code:'invalid_reply'});assert.equal(calls,2);assert.equal(vault.view().knowledge.length,0);assert.equal(vault.view().messages.filter(m=>m.role==='assistant').length,0)});
test('one malformed reply repaired without duplicating source',async t=>{const {vault,provider,service,capture,request}=await fixture(t);let calls=0;provider.respond=async()=>({text:++calls===1?'invalid':JSON.stringify(pause)});await service.talk(request(capture()));assert.equal(calls,2);assert.equal(Object.keys(vault.read().sources).length,1)});
test('revocation or source edit while cloud request is pending rejects late output',async t=>{const {vault,provider,service,capture,request}=await fixture(t);const source=capture();let resolve,started;const ready=new Promise(r=>started=r);provider.respond=()=>{started();return new Promise(r=>resolve=r)};const result=service.talk(request(source));await ready;vault.editSource({operationId:randomUUID(),id:source.sourceId,expectedRevision:1,text:'訂正した回答。'});resolve({text:JSON.stringify(pause)});await assert.rejects(result,{code:'stale_generation'});assert.equal(vault.view().messages.filter(m=>m.role==='assistant').length,0)});
test('server cancellation keeps raw answer and forbids even non-cooperative provider commit',async t=>{const {vault,provider,service,capture,request}=await fixture(t);let resolve,started;const ready=new Promise(r=>started=r);provider.respond=()=>{started();return new Promise(r=>resolve=r)};const result=service.talk(request(capture()));await ready;service.cancelAll();resolve({text:JSON.stringify(pause)});await assert.rejects(result,{code:'cancelled'});assert.equal(Object.keys(vault.read().sources).length,1);assert.equal(vault.view().messages.filter(m=>m.role==='assistant').length,0)});
test('connection change requires fresh consent and no egress',async t=>{const {provider,service,capture,request}=await fixture(t);let calls=0;provider.status=async()=>({connected:true,sharing:true,connectionId:'other'});provider.respond=async()=>{calls++;return {text:JSON.stringify(pause)}};await assert.rejects(service.talk(request(capture())),{code:'model_reconsent_required'});assert.equal(calls,0)});
test('payload excludes private sources, unrelated purposes and prior assistant wording',async t=>{const {vault,provider,service,capture,request}=await fixture(t);const privateSource=capture('共有しない印。');vault.sourcePermission({id:privateSource.sourceId,expectedRevision:1,model:false});vault.capture({operationId:randomUUID(),kind:'text',text:'別の目的の印。',purpose:'draft_reply',topic:'free'});vault.mutate(randomUUID(),{type:'fixture'},s=>{s.conversation.question='前の質問に含まれた秘密';s.conversation.messages.push({id:'old',role:'assistant',text:'秘密の応答',capturedAt:new Date().toISOString()})});let payload;provider.respond=async args=>{payload=JSON.stringify(args);return {text:JSON.stringify(pause)}};await service.talk(request(capture('今回の回答。')));assert(payload.includes('今回の回答'));for(const marker of ['共有しない印','別の目的の印','秘密の応答','前の質問に含まれた秘密'])assert(!payload.includes(marker));});
test('proposal remains unconfirmed until selected current version review',async t=>{const {vault,provider,service,capture,request}=await fixture(t);const source=capture('旅行が好きです。');provider.respond=async()=>({text:JSON.stringify({...pause,proposals:[{text:'旅行が好きです。',kind:'preference',scope:{},validTime:{},evidence:[{sourceId:source.sourceId,revision:1,start:0,end:8,quote:'旅行が好きです。'}]}]})});await service.talk(request(source));const a=vault.view().proposals[0];assert.equal(a.status,'proposed');assert.equal(vault.view().knowledge.length,0);vault.review({operationId:randomUUID(),id:a.id,expectedRevision:1,decision:'accept'});assert.equal(vault.view().knowledge[0].status,'active');});
test('a newly applicable conflict blocks the provider final-send callback',async t=>{const {vault,provider,service,capture,request}=await fixture(t);const realNow=Date.now;let time=realNow();Date.now=()=>time;t.after(()=>{Date.now=realNow});const a=vault.saveKnowledge({operationId:'active-policy',text:'現在の方針。',kind:'policy',scope:{},policy:{model:true}});vault.saveKnowledge({operationId:'future-policy',text:'相反する今後の方針。',kind:'policy',scope:{},validTime:{start:new Date(time+10000).toISOString()},policy:{model:false},conflictsWith:[a.id]});let sent=false;provider.respond=async ({beforeSend})=>{time+=20000;beforeSend();sent=true;return {text:JSON.stringify(pause)}};await assert.rejects(service.talk(request(capture())),{code:'conflict_requires_resolution'});assert.equal(sent,false);});
