import http from 'node:http';import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createApp} from '../src/server/app.mjs';
async function fixture(t){const dir=await mkdtemp(path.join(os.tmpdir(),'hz-http-'));const provider={available:false,status:async()=>({available:false,connected:false,sharing:false}),disconnect:async()=>({disconnected:true})};const app=createApp({root:path.resolve('.'),dataDir:dir,provider});await app.listen(0);const origin=app.origin;const res=await fetch(origin);const cookie=res.headers.get('set-cookie').split(';')[0];const status=await fetch(origin+'/api/status',{headers:{cookie}}).then(r=>r.json());const headers={cookie,origin,'X-CSRF-Token':status.csrf,'Content-Type':'application/json'};const request=async(route,data,extra={})=>{const r=await fetch(origin+route,{method:data===undefined?'GET':'POST',headers:{...headers,...extra},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,body:await r.json()}};t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true})});return {app,origin,request,headers};}
test('core HTTP works offline; unlock lease is browser-specific; locks erase access',async t=>{const {request,origin,app}=await fixture(t);assert.equal((await request('/api/record')).status,401);assert.equal((await request('/api/vault/create',{passphrase:'fixture passphrase',recovery:false})).status,200);const captured=await request('/api/capture',{operationId:'capture-1',text:'今日はここまで。',kind:'text',speaker:'self',purpose:'self_reflection',topic:'free'});assert.equal(captured.status,200);const r=await fetch(origin);const cookie=r.headers.get('set-cookie').split(';')[0];assert.equal((await fetch(origin+'/api/record',{headers:{cookie}})).status,401);assert.equal((await request('/api/vault/lock',{})).status,200);assert.equal(app.vault.unlocked,false);assert.equal((await request('/api/record')).status,401);await request('/api/vault/unlock',{passphrase:'fixture passphrase'});assert.equal((await request('/api/record')).body.messages[0].text,'今日はここまで。');});
test('host/origin/CSRF and malformed input fail closed',async t=>{const {request,origin}=await fixture(t);assert.equal((await request('/api/vault/create',{passphrase:'fixture passphrase'},{'X-CSRF-Token':'é'.repeat(64)})).status,403);assert.equal((await request('/api/vault/create',{passphrase:'fixture passphrase'},{origin:'https://evil.example'})).status,403);assert.equal(await new Promise(resolve=>{http.get(origin+'/api/status',{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode)})}),403);await request('/api/vault/create',{passphrase:'fixture passphrase'});assert.equal((await request('/api/capture',{operationId:'x',text:'x',kind:'speech'})).status,422);assert.equal((await request('/api/interview',{operationId:'i',sourceId:'missing',sourceRevision:1,topic:'free',purpose:'self_reflection'})).status,409);});
test('pause and resume preserve current question, answers and draft through lock',async t=>{const {request}=await fixture(t);await request('/api/vault/create',{passphrase:'fixture passphrase'});let r=await request('/api/navigate',{operationId:'nav-1',action:'topic',topic:'free'});const question=r.body.record.question;await request('/api/settings',{draftPersistence:true});await request('/api/draft',{text:'書きかけ'});r=await request('/api/navigate',{operationId:'pause-1',action:'pause'});assert.equal(r.body.record.inquiry.paused,true);assert.equal(r.body.record.question,question);await request('/api/vault/lock',{});await request('/api/vault/unlock',{passphrase:'fixture passphrase'});assert.equal((await request('/api/draft')).body.text,'書きかけ');r=await request('/api/navigate',{operationId:'resume-1',action:'resume'});assert.equal(r.body.record.inquiry.paused,false);assert.equal(r.body.record.question,question);});
test('generic opening question can be skipped without an existing bank identifier',async t=>{const {request}=await fixture(t);await request('/api/vault/create',{passphrase:'fixture passphrase'});const result=await request('/api/navigate',{operationId:'first-skip',action:'skip',questionId:null});assert.equal(result.status,200);assert(result.body.record.questionId);});
test('opening question appears without navigation or cloud and repeated reads preserve its position',async t=>{const {request}=await fixture(t);const created=await request('/api/vault/create',{passphrase:'fixture passphrase'});const first=created.body.record;assert(first.questionId,'create must offer a concrete bank question');assert.notEqual(first.question,'今、どんなことを話したい？');assert.equal(first.consent.model,false);assert.equal(first.messages.length,0);const inquiry=structuredClone(first.inquiry);for(let i=0;i<2;i++){const r=await request('/api/record');assert.equal(r.body.questionId,first.questionId);assert.deepEqual(r.body.inquiry,inquiry)}await request('/api/vault/lock',{});const reopened=await request('/api/vault/unlock',{passphrase:'fixture passphrase'});assert.equal(reopened.body.record.questionId,first.questionId);assert.deepEqual(reopened.body.record.inquiry,inquiry);});
test('an existing untouched generic opening is upgraded without changing saved sources or starting inference',async t=>{const {request,app}=await fixture(t);await request('/api/vault/create',{passphrase:'fixture passphrase'});app.vault.mutate('old-opening-fixture',{type:'fixture'},s=>{s.inquiry={};s.conversation.questionId=null;s.conversation.question='今、どんなことを話したい？'});const result=await request('/api/record');assert(result.body.questionId);assert.equal(result.body.messages.length,0);assert.equal(result.body.receipts.length,0);assert.equal(result.body.consent.model,false);});
test('automatic opening feeds the next turn and survives pause, lock and resume',async t=>{
  const {request,app}=await fixture(t);let calls=0;
  app.interview.provider.status=async()=>({available:true,connected:true,sharing:true,connectionId:'fixture'});
  app.interview.provider.respond=async({input,beforeSend})=>{beforeSend();calls++;const data=JSON.parse(input[0].content);assert.equal(data.currentQuestion.id,opening.questionId);assert.equal(data.source.text,'架空の例として、旅行の好みを説明する場面です。');const next=data.candidates.find(q=>q.id!==data.currentQuestion.id);assert(next);return {text:JSON.stringify({reply:'',question:next.text,questionId:next.id,move:'next',pause:false,proposals:[],coverage:[]})}};
  const opening=(await request('/api/vault/create',{passphrase:'fixture passphrase'})).body.record;
  assert.equal(calls,0);await request('/api/consent',{enabled:true});
  const capture=await request('/api/capture',{operationId:'flow-source',text:'架空の例として、旅行の好みを説明する場面です。',kind:'text',speaker:'self',purpose:'self_reflection',topic:'free'});
  assert.equal(capture.status,200);const source=capture.body;
  const next=await request('/api/interview',{operationId:'flow-interview',sourceId:source.sourceId,sourceRevision:source.sourceRevision,topic:'free',purpose:'self_reflection'});
  assert.equal(next.status,200,JSON.stringify(next.body));assert.equal(calls,1);assert.notEqual(next.body.record.questionId,opening.questionId);
  const question=next.body.record.question;await request('/api/navigate',{operationId:'flow-pause',action:'pause'});await request('/api/vault/lock',{});
  const reopened=(await request('/api/vault/unlock',{passphrase:'fixture passphrase'})).body.record;assert.equal(reopened.inquiry.paused,true);assert.equal(reopened.question,question);
  const resumed=(await request('/api/navigate',{operationId:'flow-resume',action:'resume'})).body.record;assert.equal(resumed.question,question);assert.equal(resumed.messages.length,2);assert.equal(calls,1);
});
