import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Vault} from '../src/core/vault.mjs';
const password='synthetic-test-password';
async function fixture(t){const dir=await mkdtemp(path.join(tmpdir(),'hitotsuzutsu-v2-'));const v=new Vault(dir);await v.create(password);t.after(async()=>{v.close();await rm(dir,{recursive:true,force:true})});return {v,dir}}
const capture=(v,text='私は旅行が好きではない。',id='capture-operation-0001')=>v.capture({operationId:id,text,kind:'text',speaker:'self',purpose:'self_reflection'});
const proposal=(v,sourceId,text='旅行が好きではない')=>v.addProposals({sourceId,sourceRevision:1,dataEpoch:v.read().dataEpoch,policyEpoch:v.read().policyEpoch,proposals:[{text,kind:'preference',scope:{purposes:['compare']},evidence:[{sourceId,revision:1,start:0,end:'私は旅行が好きではない。'.length,quote:'私は旅行が好きではない。'}]}]});

test('AC13/34/36: local capture ACK persists without provider and no plaintext reaches database/journal',async t=>{const {v,dir}=await fixture(t);const {sourceId}=capture(v);assert.equal(v.read().sources[sourceId].text,'私は旅行が好きではない。');v.lock();assert.throws(()=>v.read(),{code:'vault_locked'});await v.unlock(password);assert.equal(v.read().sources[sourceId].text,'私は旅行が好きではない。');for(const n of await readdir(dir)){const bytes=await readFile(path.join(dir,n));assert(!bytes.includes(Buffer.from('私は旅行が好きではない。')),n)}});
test('AC15: exact retry succeeds but same operation with another payload conflicts',async t=>{const {v}=await fixture(t);const first=capture(v);assert.equal(capture(v).sourceId,first.sourceId);assert.throws(()=>capture(v,'異なる内容'),{code:'operation_conflict'});assert.equal(Object.keys(v.read().sources).length,1)});
test('AC36/37: incorrect password and tampered backup fail closed',async t=>{const {v}=await fixture(t);v.lock();await assert.rejects(v.unlock('wrong-password'),{code:'unlock_failed'});await v.unlock(password);const b=JSON.parse(await v.backup(password));b.payload.data=b.payload.data.slice(0,-8)+'AAAAAAAA';await assert.rejects(v.restore(JSON.stringify(b),password),{code:'backup_invalid'})});
test('AC02/21: interpretation stays proposed, review is explicit and bound to revision',async t=>{const {v}=await fixture(t);const {sourceId}=capture(v);const [a]=proposal(v,sourceId);assert.equal(v.read().assertions[a.id].status,'proposed');assert.throws(()=>v.review({operationId:'review-operation-0001',id:a.id,expectedRevision:0,decision:'accept'}),{code:'revision_conflict'});v.review({operationId:'review-operation-0002',id:a.id,expectedRevision:1,decision:'accept'});assert.equal(v.read().assertions[a.id].status,'active')});
test('AC18/20: model fields cannot confirm or grant disclosure; old jobs cannot resurrect corrected input',async t=>{const {v}=await fixture(t);const {sourceId}=capture(v);const s=v.read();assert.throws(()=>v.addProposals({sourceId,sourceRevision:1,dataEpoch:s.dataEpoch,policyEpoch:s.policyEpoch,proposals:[{text:'x',kind:'policy',confirmed:true,policy:{disclosure:true},evidence:[]}]}),{code:'invalid_proposal'});v.editSource({operationId:'edit-operation-00001',id:sourceId,expectedRevision:1,text:'旅行については、まだ分からない。'});assert.throws(()=>v.addProposals({sourceId,sourceRevision:1,dataEpoch:s.dataEpoch,policyEpoch:s.policyEpoch,proposals:[]}),{code:'stale_generation'})});
test('AC27/28: correction invalidates dependent knowledge and already previewed packs before reuse',async t=>{const {v}=await fixture(t);const {sourceId}=capture(v);const [a]=proposal(v,sourceId);v.review({operationId:'review-operation-0001',id:a.id,expectedRevision:1,decision:'accept'});const pack=v.previewPack({operationId:'preview-operation-001',purpose:'compare',query:'旅行',audience:'self',destination:'file',context:{}});assert.equal(pack.items.length,1);v.editSource({operationId:'edit-operation-00001',id:sourceId,expectedRevision:1,text:'今は旅行を楽しんでいる。'});assert.equal(v.read().assertions[a.id].status,'invalidated');assert.throws(()=>v.exportPack({id:pack.id,expectedRevision:pack.revision,format:'markdown'}),{code:'pack_stale'})});
test('AC23/25/49: purpose and disclosure filter before packing; revocation blocks export',async t=>{const {v}=await fixture(t);v.saveKnowledge({operationId:'knowledge-op-000001',text:'家族の事情という私的な理由',kind:'fact',scope:{purposes:['draft_reply']},policy:{model:false,disclosure:false}});v.saveKnowledge({operationId:'knowledge-op-000002',text:'今回は辞退する',kind:'policy',scope:{purposes:['draft_reply']},policy:{model:true,disclosure:true}});let p=v.previewPack({operationId:'preview-operation-001',purpose:'draft_reply',query:'辞退',audience:'external',destination:'file',context:{}});assert.equal(p.items.length,1);assert(!p.text.includes('家族'));v.setConsent(true);p=v.previewPack({operationId:'preview-operation-002',purpose:'draft_reply',query:'辞退',audience:'external',destination:'chatgpt',context:{}});v.setConsent(false);assert.throws(()=>v.exportPack({id:p.id,expectedRevision:p.revision,format:'json'}),{code:'pack_stale'})});
test('AC24/50: mandatory constraints are not discarded by a small limit; expired data is excluded',async t=>{const {v}=await fixture(t);v.saveKnowledge({operationId:'knowledge-op-000001',text:'必ず予算内にする',kind:'policy',hardConstraint:true,scope:{purposes:['compare']},policy:{}});v.saveKnowledge({operationId:'knowledge-op-000002',text:'必ず返品可能にする',kind:'policy',hardConstraint:true,scope:{purposes:['compare']},policy:{}});v.saveKnowledge({operationId:'knowledge-op-000003',text:'昔の条件',kind:'state',validTime:{end:'2000-01-01'},scope:{purposes:['compare']},policy:{}});const p=v.previewPack({operationId:'preview-operation-001',purpose:'compare',query:'',audience:'self',destination:'file',context:{},limit:1});assert.equal(p.items.length,2);assert(!p.text.includes('昔'))});
test('AC05: task-only adoption cannot leak into another task',async t=>{const {v}=await fixture(t);const {sourceId}=capture(v);const [a]=proposal(v,sourceId);assert.throws(()=>v.review({operationId:'review-operation-0001',id:a.id,expectedRevision:1,decision:'task_only'}),{code:'task_required'});v.review({operationId:'review-operation-0002',id:a.id,expectedRevision:1,decision:'task_only',taskId:'task-a',expiresAt:new Date(Date.now()+600000).toISOString()});const p=v.previewPack({operationId:'preview-operation-001',purpose:'compare',taskId:'task-b',query:'旅行',audience:'self',destination:'file',context:{}});assert.equal(p.items.length,0)});
test('AC30/31/32: deletion purges source+derivatives and old backups cannot revive them',async t=>{const {v}=await fixture(t);const {sourceId}=capture(v);const [a]=proposal(v,sourceId);v.review({operationId:'review-operation-0001',id:a.id,expectedRevision:1,decision:'accept'});const old=await v.backup(password);v.deleteSource({operationId:'delete-operation-001',id:sourceId,expectedRevision:1});assert(!JSON.stringify(v.read()).includes('旅行'));await v.restore(old,password);assert(!v.read().sources[sourceId]);assert(!v.read().assertions[a.id]);assert.equal(v.read().consent.model,false)});
test('AC16/17: two instances serialize updates and stale edits fail; thrown transaction commits nothing',async t=>{const {v,dir}=await fixture(t);const other=new Vault(dir);await other.unlock(password);t.after(()=>other.close());const {sourceId}=capture(v);other.editSource({operationId:'edit-operation-00001',id:sourceId,expectedRevision:1,text:'訂正'});assert.throws(()=>v.editSource({operationId:'edit-operation-00002',id:sourceId,expectedRevision:1,text:'古い画面'}),{code:'revision_conflict'});const rev=v.read().revision;assert.throws(()=>v.mutate('fault-operation-0001',{},s=>{s.sources={};throw Error('synthetic failure')}));assert.equal(v.read().revision,rev);assert(v.read().sources[sourceId])});
test('AC33: deleting a source must not erase independent direct knowledge',async t=>{const {v}=await fixture(t);const {sourceId}=capture(v);const a=v.saveKnowledge({operationId:'knowledge-op-000001',text:'短く返してほしい',kind:'preference',scope:{purposes:['draft_reply']},policy:{}});v.deleteSource({operationId:'delete-operation-001',id:sourceId,expectedRevision:1});assert.equal(v.read().assertions[a.id].status,'active')});
test('historical time precision is preserved independently of capture or review date',async t=>{const {v}=await fixture(t);const result=v.saveKnowledge({operationId:'historical',text:'2025年の夏は夜勤だった。',kind:'state',scope:{},validTime:{start:'2025-06-01',end:'2025-09-01',precision:'season',label:'2025年の夏'},policy:{}});const a=v.read().assertions[result.id];assert.equal(a.validTime.precision,'season');assert.equal(a.validTime.label,'2025年の夏');const p=v.previewPack({operationId:'historical-pack',purpose:'plan',audience:'self',destination:'file',context:{}});assert.equal(p.items.length,0);assert.equal(p.omitted[0].reason,'expired');});
test('source evidence cannot clip negation at the middle of a sentence',async t=>{const {v}=await fixture(t);const {sourceId}=capture(v);assert.throws(()=>v.addProposals({sourceId,sourceRevision:1,dataEpoch:v.read().dataEpoch,policyEpoch:v.read().policyEpoch,proposals:[{text:'旅行が好き',kind:'preference',scope:{},evidence:[{sourceId,revision:1,start:2,end:7,quote:'旅行が好き'}]}]}));assert.equal(v.view().proposals.length,0);});
test('restored minimal scope/time are normalized and remain reviewable and selectable',async t=>{const {encryptBackup}=await import('../src/core/crypto.mjs');const {v}=await fixture(t);const result=v.saveKnowledge({operationId:'minimal-schema',text:'テスト用の好み。',kind:'preference',scope:{},policy:{}});const incoming=v.read();incoming.id='foreign-vault';const a=incoming.assertions[result.id];delete a.scope;delete a.validTime;const content=await encryptBackup(incoming,password);v.deleteKnowledge({operationId:'remove-original',id:a.id,expectedRevision:1});a.id='imported-assertion';incoming.assertions={[a.id]:a};await v.restore(await encryptBackup(incoming,password),password,{acknowledgeUnknownHistory:true});const restored=v.read().assertions[a.id];assert.deepEqual(restored.scope.conditions,[]);assert.equal(restored.validTime.precision,'unknown');v.review({operationId:'review-restored',id:a.id,expectedRevision:restored.revision,decision:'accept'});assert.equal(v.previewPack({operationId:'normalized-pack',purpose:'conversation',audience:'self',destination:'file',context:{}}).items.length,1);});
test('explicit conflicts block before top-k selection and resolve by withdrawal',async t=>{const {v}=await fixture(t);const a=v.saveKnowledge({operationId:'conflict-one',text:'今月は新しい依頼を断る。',kind:'policy',hardConstraint:true,scope:{purposes:['draft_reply']},policy:{}});const b=v.saveKnowledge({operationId:'conflict-two',text:'今月は新しい依頼を受ける。',kind:'policy',hardConstraint:true,scope:{purposes:['draft_reply']},policy:{},conflictsWith:[a.id]});assert.throws(()=>v.previewPack({operationId:'conflict-pack',purpose:'draft_reply',audience:'self',destination:'file',context:{},limit:1}),{code:'conflict_requires_resolution'});v.withdraw({operationId:'resolve-conflict',id:b.id,expectedRevision:1});assert.equal(v.previewPack({operationId:'resolved-pack',purpose:'draft_reply',audience:'self',destination:'file',context:{},limit:1}).items.length,1);});
test('a conflict that becomes applicable after preview blocks export even without an edit',async t=>{const {v}=await fixture(t);const realNow=Date.now;let time=realNow();Date.now=()=>time;t.after(()=>{Date.now=realNow});const a=v.saveKnowledge({operationId:'timed-first',text:'適用中の方針。',kind:'policy',scope:{},policy:{}});v.saveKnowledge({operationId:'timed-second',text:'後で適用される相反する方針。',kind:'policy',scope:{},validTime:{start:new Date(time+10000).toISOString()},policy:{},conflictsWith:[a.id]});const p=v.previewPack({operationId:'timed-preview',purpose:'plan',audience:'self',destination:'file',context:{}});time+=20000;assert.throws(()=>v.exportPack({id:p.id,expectedRevision:p.revision,format:'markdown'}),{code:'conflict_requires_resolution'});});
