const $=id=>document.getElementById(id);
let csrf='',session=null,record=null,topic='start',pace='slow',model=null,active=false,paused=false,busy=false,voiceAbort=null,chatAbort=null,speakAbort=null,settleTimer=null,authPoll=null,revision=0,latestText='',failedTurn=null;
const stopWords=/^(?:ちょっと|少し)?(?:待って|まって|ストップ|一旦停止)[。！!\s]*$/;
const endWords=/^(?:今日はここまで|終わり|おわり|終了|やめる)[。！!\s]*$/;
const safeNode=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n};
function status(text,thinking=false){$('status').textContent=text;$('orb').classList.toggle('thinking',thinking)}
function error(text){$('error').textContent=text}
async function api(path,body,options={}){const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body),signal:options.signal,cache:'no-store'});let data;try{data=await res.json()}catch{throw Error('接続を確かめて、もう一度試してください。')}if(!res.ok)throw Object.assign(Error(data.message||'操作を完了できませんでした。'),{code:data.error});return data}
function drawRecord(){if(!record)return;$('question').textContent=record.question;$('transcriptBody').replaceChildren();for(const m of record.messages){const div=safeNode('div','',`line ${m.role==='user'?'user':''}`);div.append(safeNode('div',m.role==='user'?(m.kind==='navigation'?'話題の変更':'あなた'):'聞き手','speaker'),safeNode('p',m.text));$('transcriptBody').append(div)}if(!record.messages.length)$('transcriptBody').append(safeNode('p','話した内容は、ここに残ります。','quiet'));$('historyBody').replaceChildren();const count=record.messages.filter(m=>m.role==='user'&&m.kind==='raw_answer').length;$('historyBody').append(safeNode('p',count?`${count}回の発言を保存しています。`:'まだ記録はありません。'));for(const m of record.messages.filter(m=>m.role==='user'&&m.kind==='raw_answer')){const div=safeNode('div','','record');div.append(safeNode('p',m.text));$('historyBody').append(div)}$('storageState').textContent=record.messages.length?'このMacに保存済み':'話した内容は、このMacに保存';}
function controls(){const signed=session?.status==='connected'&&session?.sharing;$('connect').hidden=signed;$('connect').disabled=session?.signingIn===true;$('start').hidden=!signed||active;$('pause').hidden=!active;$('finish').hidden=!signed||!active;$('modeLinks').hidden=!signed;$('loginNote').hidden=signed;$('disconnect').hidden=!signed;$('pause').textContent=paused?'話を再開':'少し待って';$('start').textContent=record?.messages.length?'話の続きをはじめる':'話しはじめる';$('accountInfo').textContent=signed?`${session.identity?.name||session.identity?.email||'ChatGPT'} · ChatGPTの利用枠を使用`:'ChatGPT未接続';$('start').disabled=busy;$('textMode').disabled=busy;$('send').disabled=busy;$('skip').disabled=busy;$('applySettings').disabled=busy;}
async function refresh(){session=await api('/api/status');csrf=session.csrf;controls();if(session.sharing){record=await api('/api/record');topic=record.topic;$('topic').value=topic;drawRecord();const catalog=await api('/api/models');model=catalog.selected;status('準備できました');$('voiceInfo').textContent='音声はこのMacで認識・読み上げをします。元の設計書と会話の文章はChatGPTに送ります。';return true}status(session.signingIn?'ChatGPTでの操作を待っています':'');if(session.status==='connected'&&!session.sharing)error('ChatGPTの利用枠を使う許可が必要です。もう一度接続してください。');return false}
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('settingsButton').onclick=()=>$('settings').showModal();$('historyButton').onclick=()=>{drawRecord();$('history').showModal()};
$('connect').onclick=async()=>{error('');const popup=window.open('about:blank','hitotsuzutsu-signin');if(popup)popup.opener=null;$('connect').disabled=true;try{await api('/api/auth/start',{});status('ChatGPTでサインインしてください');let opened=false;const until=Date.now()+10*60*1000;clearInterval(authPoll);authPoll=setInterval(async()=>{try{const p=await api('/api/auth/pending');if(p.url&&!opened){opened=true;if(popup&&!popup.closed)popup.location.href=p.url;else{const link=safeNode('a','ChatGPTのサインインを開く');link.href=p.url;link.target='_blank';link.rel='noopener noreferrer';$('error').replaceChildren(link)}}const next=await api('/api/status');session=next;if(next.sharing){clearInterval(authPoll);authPoll=null;error('');await refresh()}else if(p.errorCode||Date.now()>until){clearInterval(authPoll);authPoll=null;error('サインインを完了できませんでした。もう一度試せます。');session.signingIn=false;controls()}else controls()}catch{clearInterval(authPoll);authPoll=null;error('接続を確認できませんでした。ページを開き直してください。')}},1000)}catch(e){popup?.close();error(e.message);$('connect').disabled=false}};
function stopListening(){clearTimeout(settleTimer);settleTimer=null;voiceAbort?.abort();voiceAbort=null;$('orb').style.setProperty('--level','1')}
async function stopAudio(){stopListening();speakAbort?.abort();speakAbort=null;try{await api('/api/stop-audio',{})}catch{}}
async function pauseConversation(){paused=!paused;if(paused){revision++;chatAbort?.abort();busy=false;await stopAudio();status('待っています。ゆっくりどうぞ。')}else{error('');await listen()}controls()}
async function finish(){active=false;paused=false;revision++;chatAbort?.abort();busy=false;await stopAudio();status('今日はここまで。続きは、いつでも。');$('caption').textContent='';$('composer').hidden=true;controls()}
const voiceErrors={speech_permission:'Macの「システム設定 → プライバシーとセキュリティ → 音声認識」で、このアプリを許可してください。',microphone_permission:'Macの「システム設定 → プライバシーとセキュリティ → マイク」で、このアプリを許可してください。',on_device_unavailable:'このMacで日本語の音声認識を利用できません。文字で会話を続けられます。',recognition_unavailable:'音声を認識できませんでした。もう一度始めるか、文字で続けられます。',no_microphone:'マイクを確認してから、もう一度始めてください。'};
async function listen(){if(!active||paused||busy)return;stopListening();const token=revision;const controller=new AbortController();voiceAbort=controller;let chunksByTurn=new Map();latestText='';status('聞いています');try{const res=await fetch('/api/voice',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:'{}',signal:controller.signal});if(!res.ok)throw Error('マイクを開始できませんでした。少し待って再開してください。');const reader=res.body.getReader();const decoder=new TextDecoder();let pending='';let gotReady=false;while(true){const r=await reader.read();if(r.done)break;pending+=decoder.decode(r.value,{stream:true});let idx;while((idx=pending.indexOf('\n'))>=0){const line=pending.slice(0,idx);pending=pending.slice(idx+1);if(!line.trim())continue;const e=JSON.parse(line);if(token!==revision||controller.signal.aborted)return;if(e.type==='error')throw Error(voiceErrors[e.code]||'音声を開始できませんでした。文字でも続けられます。');if(e.type==='ready'){gotReady=true;status('聞いています')}if(e.type==='transcript'&&typeof e.text==='string'){chunksByTurn.set(e.turn,e.text);latestText=[...chunksByTurn.values()].filter(Boolean).join(' ');$('caption').textContent=latestText;const lv=1+Math.min(latestText.length%7,5)/5;$('orb').style.setProperty('--level',String(lv));clearTimeout(settleTimer);if(latestText.trim())settleTimer=setTimeout(async()=>{if(token!==revision||paused||!active)return;const text=latestText.trim();stopListening();if(endWords.test(text)){await finish();return}if(stopWords.test(text)){await pauseConversation();return}await submit(text,'answer',true)},pace==='slow'?3600:2200)}}}if(!controller.signal.aborted&&active&&!paused&&!busy)throw Error(gotReady?'音声接続が切れました。再開できます。':'マイクを開始できませんでした。')}catch(e){if(controller.signal.aborted||token!==revision)return;paused=true;status('音声をいったん止めました');error(e.message);$('composer').hidden=false;controls()}finally{if(voiceAbort===controller)voiceAbort=null}}
async function speak(messageId){const controller=new AbortController();speakAbort=controller;try{status('話しています');const result=await api('/api/speak',{messageId},{signal:controller.signal});if(!result.spoken)throw Error('speech_failed')}catch(e){if(!controller.signal.aborted)error('読み上げを再生できませんでした。画面の質問を見て、そのまま話せます。')}finally{if(speakAbort===controller)speakAbort=null}}
async function submit(text,action='answer',fromVoice=false){if(busy||!text.trim())return;stopListening();error('');busy=true;controls();const token=revision;const controller=new AbortController();chatAbort=controller;const requestId=failedTurn?.text===text&&failedTurn?.action===action?failedTurn.requestId:crypto.randomUUID();failedTurn={text,action,requestId};status('考えています',true);$('caption').textContent=text;try{const result=await api('/api/chat',{text,topic,action,requestId,model},{signal:controller.signal});if(token!==revision)return;failedTurn=null;record=result.record;drawRecord();$('caption').textContent=result.answer.reply||'';$('message').value='';$('guide').textContent='';if(fromVoice&&active&&!paused){const last=record.messages.filter(m=>m.role==='assistant').at(-1);await speak(last.id)}if(result.answer.pause){active=false;paused=false;status('ここで一区切り。続きは、いつでも。')}else status(active?'聞いています':'そのまま、続きをどうぞ。')}catch(e){if(controller.signal.aborted||token!==revision)return;error(e.message);status('回答はそのまま残しています');$('message').value=text;$('composer').hidden=false;paused=active;try{record=await api('/api/record');drawRecord()}catch{}}finally{if(chatAbort===controller){chatAbort=null;busy=false;controls();if(token===revision&&fromVoice&&active&&!paused)listen()}}}
$('start').onclick=async()=>{error('');active=true;paused=false;revision++;$('composer').hidden=true;controls();await listen()};$('pause').onclick=pauseConversation;$('finish').onclick=finish;
$('textMode').onclick=async()=>{await stopAudio();active=false;paused=false;revision++;controls();$('composer').hidden=!$('composer').hidden;status('');if(!$('composer').hidden)$('message').focus()};
$('composer').onsubmit=e=>{e.preventDefault();submit($('message').value,'answer',false)};$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('composer').requestSubmit()}};
$('skip').onclick=()=>submit('今の質問は飛ばして、別の話題に進みたい。','skip',active);
$('applySettings').onclick=()=>{topic=$('topic').value;pace=$('pace').value;$('settings').close();$('topicLabel').textContent=$('topic').selectedOptions[0].textContent;if(record?.topic!==topic&&session?.sharing)submit('このテーマから話したい。','skip',active)};
$('disconnect').onclick=async()=>{await finish();await api('/api/auth/disconnect',{});record=null;model=null;$('settings').close();await refresh()};
$('export').onclick=()=>{if(!record){$('historyBody').textContent='まだ記録はありません。';return}const blob=new Blob([JSON.stringify(record,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ひとつずつ-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.addEventListener('pagehide',()=>{active=false;revision++;stopListening();chatAbort?.abort();speakAbort?.abort();clearInterval(authPoll)});
const mc=document.modelContext;if(mc?.registerTool){const life=new AbortController();for(const tool of [{name:'read_current_interview',title:'今の問いを見る',description:'Read the visible question and conversation status. No answers or credentials returned.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({question:$('question').textContent,status:$('status').textContent,active,paused})},{name:'pause_interview',title:'会話を一時停止',description:'Pause microphone capture and speech. Does not erase answers or start a paid operation.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{if(active&&!paused)await pauseConversation();return {paused:paused||!active}}}]){try{Promise.resolve(mc.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true})}
refresh().catch(()=>{status('接続できませんでした');error('この画面を開き直してください。')});
